cloud\_fs.filesystems.FileSystemError
=====================================

.. currentmodule:: cloud_fs.filesystems

.. autoexception:: FileSystemError